version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=railway
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=crpbhiohpqhkiUVvnogACyLdeCtpUUad
    ports:
      - "3306:3306"

  web:
    build: .
    command: gunicorn prediction_system.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1  # Для отладки
      - DATABASE=railway
      - SQL_ENGINE=django.db.backends.mysql
      - SQL_DATABASE=railway
      - SQL_USER=root
      - SQL_PASSWORD=crpbhiohpqhkiUVvnogACyLdeCtpUUad
      - SQL_HOST=mysql.railway.internal
      - SQL_PORT=3306

  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
